# Generated by Django 3.1.7 on 2021-04-04 01:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210404_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
        ),
    ]
