# Generated by Django 3.1.7 on 2021-04-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210404_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ManyToManyField(related_name='get_posts', to='blog.Categoria', verbose_name='Categorias'),
        ),
    ]
