# Generated by Django 3.1.7 on 2021-04-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(max_length=100, unique=True, verbose_name='Nombre clave')),
                ('nombre', models.CharField(max_length=200, verbose_name='Red social')),
                ('enlace_web', models.URLField(blank=True, null=True, verbose_name='Enlace web')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Enlace',
                'verbose_name_plural': 'Enlaces',
                'ordering': ['nombre'],
            },
        ),
    ]
